FROM trinityctat/starfusion:1.8.1
MAINTAINER jennyl.smith12@gmailcom

### very simple script to just update ubuntu since I need the image to be hosted on quay.io
RUN apt-get update && yes|apt-get upgrade
